version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash -c "gcc -o main main.c && bundle exec rspec && rm Gemfile.lock"