version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/bash -c "make clean && make && bundle exec rspec && rm Gemfile.lock && rm test.db"